// @flow
export const ADD_SECTION = 'ADD_SECTION';
export const DELETE_SECTION = 'DELETE_SECTION';
export const EDIT_SECTION = 'EDIT_SECTION';
export const CHANGE_EDIT_MODE = 'CHANGE_EDIT_MODE';
export const SELECT_TEMPLEATE_SECTION = 'SELECT_TEMPLEATE_SECTION';

export const EDIT_TITLE = 'EDIT_TITLE';
export const UPDATE_LIST = 'UPDATE_LIST';
export const UPLOAD_EYE_CATCH = 'UPLOAD_EYE_CATCH';
export const CHANGE_UPLOAD_EDIT_MODE = 'CHANGE_UPLOAD_EDIT_MODE';
export const CHANGE_UPLOAD_TITLE_EDIT_MODE = 'CHANGE_UPLOAD_TITLE_EDIT_MODE';
